server:
  port: 8083
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: auth-service
  profiles:
    active: local

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true

  default-produces-media-type: application/json
  show-actuator: true