server:
  port: 8081
  forward-headers-strategy: framework


spring:
  profiles:
    active: local
  application:
    name: user-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  show-actuator: true

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always