eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka


spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/micro-service-test
    username: my_local
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
