server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/micro-service-test
    username: my_local
    password: 123456
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update  # use 'validate' or 'none' in production
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  show-actuator: true

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always