server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: product-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  show-actuator: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

