server:
  port: 8082
  forward-headers-strategy: framework

spring:
  profiles:
    active: local
  application:
    name: product-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  show-actuator: true

eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka
      defaultZone: http://discovery-service:8761/eureka

